### ISSUE TITLE
Seemingly impossible panic: tomb.Go called after all goroutines terminated

### ISSUE THREAD

**Issue by myitcv** [go-tomb/tomb#24]
Firstly: thanks for the awesome package.

Secondly, I must be missing something obvious here, but the following call stack would seem, from the panic, to be impossible:

```
panic: tomb.Go called after all goroutines terminated [recovered]
        panic: tomb.Go called after all goroutines terminated

goroutine 937 [running]:
github.com/govim/govim.(*govimImpl).DoProto.func1(0xc000171d40, 0xc00044fdf8)
        /home/myitcv/gostuff/src/github.com/myitcv/govim/channel_cmds.go:127 +0x1b6
panic(0x674360, 0x738b40)
        /home/myitcv/gos/src/runtime/panic.go:961 +0x15d
gopkg.in/tomb%2ev2.(*Tomb).Go(0xc000171de8, 0xc0004fcac0)
        /home/myitcv/gostuff/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:155 +0x106
github.com/govim/govim.(*govimImpl).run(0xc000171d40, 0xc0004d2360, 0xc0004cad80)
        /home/myitcv/gostuff/src/github.com/myitcv/govim/govim.go:472 +0x1c78
github.com/govim/govim.(*govimImpl).Run.func1(0x4d95e3, 0xc000218d70)
        /home/myitcv/gostuff/src/github.com/myitcv/govim/govim.go:404 +0x2a
github.com/govim/govim.(*govimImpl).DoProto(0xc000171d40, 0xc0003b0e20, 0x0, 0x0)
        /home/myitcv/gostuff/src/github.com/myitcv/govim/channel_cmds.go:131 +0x6a
github.com/govim/govim.(*govimImpl).Run(0xc000171d40, 0x6f89e0, 0xc0003b0f20)
        /home/myitcv/gostuff/src/github.com/myitcv/govim/govim.go:403 +0x52
github.com/govim/govim/testdriver.(*TestDriver).runGovim(0xc0001717a0, 0x0, 0x0)
        /home/myitcv/gostuff/src/github.com/myitcv/govim/testdriver/testdriver.go:383 +0x73
github.com/govim/govim/testdriver.(*TestDriver).tombgo.func1(0x0, 0x0)
        /home/myitcv/gostuff/src/github.com/myitcv/govim/testdriver/testdriver.go:326 +0x41
gopkg.in/tomb%2ev2.(*Tomb).run(0xc000171868, 0xc0005fc0a0)
        /home/myitcv/gostuff/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:163 +0x38
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /home/myitcv/gostuff/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:159 +0xba
```

Because the very fact the call stack is as shown surely indicates there is at least one go routine that has not terminated, i.e. the one that is attempting to call `tomb.Go`?

**Comment by myitcv** [comment]
On further investigation, it seems the panic is somewhat misleading. Because in this case at least the tomb is already dying when we attempt to call `tomb.Go`. The reason the tomb is dying in my case is clear, but I'll leave this issue open as a placeholder for perhaps tidying up the panic message in this case at least.

**Comment by glinton** [comment]
Feels related to #28

Can be triggered as follows:

https://play.golang.com/p/pAyHtEyNCVK
```go
package main

import (
	"time"

	"gopkg.in/tomb.v2"
)

func main() {
	t := tomb.Tomb{}
	t.Go(func() error { return nil })
	time.Sleep(time.Millisecond)
	t.Go(func() error { return nil })
}
```
